### ISSUE TITLE
Refresh soal saat belum ada jawaban

### ISSUE THREAD

**Issue by akhmadzaini** [akhmadzaini/CBT#20]
Error ketika refresh soal dan peserta belum pernah menjawab

**Comment by oediek** [comment]
saat siswa di reset dari server blank screen

**Comment by oediek** [comment]
ilustrasi paling mudah = saat siswa mengerjakan, terus proktor reset > seharusnya siswa minta login lagi. 
jadi ada validasi status. 
saat status belum login yang tampil form login
saat status mengerjakan yang tampil form mengerjakan kecuali validasi login tidak terpenuhi maka ke 
       form login

**Comment by akhmadzaini** [comment]
fix ==> https://github.com/akhmadzaini/CBT/commit/f17c29dc9a4ca6f7b50e68d98c5e59aee6f657e1
