### ISSUE TITLE
tambah sesi di cetak php

### ISSUE THREAD

**Issue by oediek** [akhmadzaini/CBT#24]
baris 39 =  $sql = "SELECT nis, login, password, sesi, server, nama FROM peserta WHERE ujian_id = '$ujian_id'

baris 47 = $siswa[]=array($r->login,$r->password,$r->sesi,$r->server,$r->nis,substr($r->nama, 0, 25));

baris 86-112 =
 $pdf->Cell(189 ,6,'',0,1);//end of line
		  $pdf->SetFont('Arial','',8);
		  $pdf->Cell(30 ,4,'',0,0);$pdf->Cell(10 ,4,'User',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][0],0,0);
		  $pdf->Cell(55 ,4,'',0,0);$pdf->Cell(10 ,4,'User',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][0],0,1);
		  $pdf->Cell(30 ,4,'',0,0);$pdf->Cell(10 ,4,'Pass',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][1],0,0);
		  $pdf->Cell(55 ,4,'',0,0);$pdf->Cell(10 ,4,'Pass',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][1],0,1);
		  $pdf->Cell(30 ,4,'',0,0);$pdf->Cell(10 ,4,'Sesi',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][2],0,0);
		  $pdf->Cell(55 ,4,'',0,0);$pdf->Cell(10 ,4,'Sesi',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][2],0,1);
		  $pdf->Cell(30 ,4,'',0,0);$pdf->Cell(10 ,4,'Server',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][3],0,0);
		  $pdf->Cell(55 ,4,'',0,0);$pdf->Cell(10 ,4,'Server',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][3],0,1);
		  $pdf->Cell(30 ,4,'',0,0);$pdf->Cell(10 ,4,'NISN',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][4],0,0);
		  $pdf->Cell(55 ,4,'',0,0);$pdf->Cell(10 ,4,'NISN',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][4],0,1);
		  $pdf->Cell(30 ,4,'',0,0);$pdf->Cell(10 ,4,'Nama',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][5],0,0);
		  $pdf->Cell(55 ,4,'',0,0);$pdf->Cell(10 ,4,'Nama',0,0);$pdf->Cell(3 ,4,':',0,0);
		  $pdf->Cell(30 ,4,$siswa[$nourut][5],0,1);

**Comment by akhmadzaini** [comment]
fix
