### ISSUE TITLE
fungsi TEXT "ukuran font soal" di form soal siswa apa memang dibuat  begitu?

### ISSUE THREAD

**Issue by oediek** [akhmadzaini/CBT#30]

**Comment by akhmadzaini** [comment]
Ngganti ukuran font di lembar soal tidak akan bekerja ketika gurune memformat ukuran lewat MS word, soale hasil pemformatan di ms word iku dadi tag html + css. lek pengen iso dibesar dan kecilkan, maka soal harus bersih dari pemformatan ms word

**Comment by oediek** [comment]
ok
