### ISSUE TITLE
skor soal esay ditambah

### ISSUE THREAD

**Issue by oediek** [akhmadzaini/CBT#34]
skor soal esay ditambah kolom (ben jelas tak kei scrip e)

  }else if($kolom->length == 4){
        // Jika baris merupakan baris soal essay
        $soal = array(	
          'konten' 	=> get_inner_html($kolom->item(1)),
          'skor' 		=> (float)$kolom->item(2)->nodeValue,
          'indikator' 		=> $kolom->item(3)->nodeValue,
          'jawaban'	=> '',  							
          'essay'		=> 1

**Comment by akhmadzaini** [comment]
https://github.com/akhmadzaini/CBT/commit/47e29db70e525d854549ee4a260867bdc294fdb2
