### ISSUE TITLE
excel sheet hasil (jawabanConcat = jawabanConcat + " ")

### ISSUE THREAD

**Issue by oediek** [akhmadzaini/CBT#36]
Values(i, 11 + n) = jawaban
        
        'tambah jumlah terjawab jika jawaban tidak kosong
        If IsNull(jawaban) Then
            kosong = kosong + 1
            jawabanConcat = jawabanConcat + " "
        Else
            'tambah jumlah jawaban benar jika benar
            jawaban = Left(jawaban, 1)
            kunci = Left(kunci, 1)
            If StrComp(jawaban, kunci, vbTextCompare) = 0 Then
                benar = benar + 1
                Values(i, 4) = Values(i, 4) + CDbl(skor)
            Else
                salah = salah + 1
            End If
            jawabanConcat = jawabanConcat + jawaban
        End If
        
      Next n

**Comment by oediek** [comment]
ganti iki ae
If IsNull(jawaban) Then
            kosong = kosong + 1
            jawabanConcat = jawabanConcat + " "
        Else
            'tambah jumlah jawaban benar jika benar
            jawaban = Left(jawaban, 1)
            kunci = Left(kunci, 1)
            If StrComp(jawaban, kunci, vbTextCompare) = 0 Then
                benar = benar + 1
                Values(i, 4) = Values(i, 4) + CDbl(skor)
                jawabanConcat = jawabanConcat + jawaban
            Else
                salah = salah + 1
                jawabanConcat = jawabanConcat + LCase(jawaban)
            End If
        End If

**Comment by akhmadzaini** [comment]
wis
https://github.com/akhmadzaini/CBT/commit/f6babb8a77ee4612d701794a7c97bfbdbfb0aa14
