### ISSUE TITLE
tambahan sycron untuk sync semua

### ISSUE THREAD

**Issue by oediek** [akhmadzaini/CBT#37]
if($id_server != 'all'){
		if($id_server != ''){
		  $this->db->where('server', $id_server);
		  $jml = $this->db->count_all_results('peserta');
		  if($jml == 0){
			json_output(200, array('pesan' => 'server_gagal'));
			die();
		  }
		}
	}

		$token = string_acak(5);
		$backup_dir = FCPATH . 'backup-' . $token;
		mkdir($backup_dir);
    
    $data['ujian'] = $this->db->get('ujian')->result();
		$data['soal'] = $this->db->get('soal')->result();
		$data['pilihan_jawaban'] = $this->db->get('pilihan_jawaban')->result();
    if($id_server != '') $data['peserta'] = $this->db->get_where('peserta', array('server' => $id_server))->result();
    if($id_server == 'all') $data['peserta'] = $this->db->get('peserta')->result();

**Comment by akhmadzaini** [comment]
https://github.com/akhmadzaini/CBT/commit/96851ac98bfa95da0e235ae5ce48d10abd728257 done
