### ISSUE TITLE
edit tampilan dashboard proktor

### ISSUE THREAD

**Issue by oediek** [akhmadzaini/CBT#38]
function index(){
		$data['jml_ujian'] = $this->_jml_ujian();
		$data['jml_ujian_lalu'] = $this->_jml_ujian('lalu');
		$data['jml_ujian_lanjut'] = $this->_jml_ujian('lanjut');
		$data['jml_ujian_progres'] = $this->_jml_ujian('progres');

		$data['ujian_progres'] = $this->_list_ujian('progres');
		$data['ujian_lanjut'] = $this->_list_ujian('lanjut');
		$data['acak'] = $this->_list_ujian('acak');
		$data['alokasi'] = $this->_list_ujian('alokasi');

		$this->load->view('proktor/dashboard', $data);
	}

                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nama Ujian</th>
                                            <th>Mulai</th>
                                            <th>Selesai</th>
                                            <th>Acak</th>
                                            <th>waktu</th>
                                            <th>Jml.Peserta</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php $n = 1?>
                                        <?php foreach($ujian_progres as $ujian):?>
                                            <tr>
                                                <td><?=$n++?></td>
                                                <td>
                                                  <a href="?d=proktor&c=monitor&m=peserta&ujian_id=<?=$ujian->ujian_id?>"><?=$ujian->judul?></a> 
                                                  <span class="label bg-pink"><?=$ujian->ujian_id?></span>
                                                  <span class="label bg-lime"><?=$ujian->jml_soal?> soal</span> 
                                                  <span class="label bg-light-blue">berlangsung</span>
                                                </td>
                                                <td><?=mysqldate_to_str($ujian->mulai)?></td>
                                                <td><?=mysqldate_to_str($ujian->selesai)?></td>
                                                <td><?=$ujian->acak?></td>
                                                <td><?=$ujian->alokasi?></td>
                                                <td><?=$ujian->jml_peserta?></td>
                                            </tr>
                                        <?php endforeach?>
                                        <?php foreach($ujian_lanjut as $ujian):?>
                                            <tr>
                                                <td><?=$n++?></td>
                                                <td>
                                                  <a href="?d=proktor&c=monitor&m=peserta&ujian_id=<?=$ujian->ujian_id?>"><?=$ujian->judul?></a> 
                                                  <span class="label bg-pink"><?=$ujian->ujian_id?></span>
                                                  <span class="label bg-lime"><?=$ujian->jml_soal?> soal</span> 
                                                  <span class="label bg-deep-puple">selanjutnya</span>
                                                </td>
                                                <td><?=mysqldate_to_str($ujian->mulai)?></td>
                                                <td><?=mysqldate_to_str($ujian->selesai)?></td>
                                                <td><?=$ujian->acak?></td>
                                                <td><?=$ujian->alokasi?></td>
                                                <td><?=$ujian->jml_peserta?></td>
                                            </tr>
                                        <?php endforeach?>

**Comment by akhmadzaini** [comment]
https://github.com/akhmadzaini/CBT/commit/86efd32638e5644436e26d8b9417dd37c71c57a2 done
